@startuml
actor 管理员
participant index.jsp
participant BookInuseController
participant IBookInuseService
participant BookInuseMapper

管理员 -> index.jsp: 登录成功
activate index.jsp
index.jsp -> BookInuseController:查询所有上架图书
activate BookInuseController
BookInuseController -> IBookInuseService:查询所有上架图书
activate IBookInuseService
IBookInuseService -> BookInuseMapper:查询所有上架图书
activate BookInuseMapper
BookInuseMapper --> IBookInuseService:返回上架信息
deactivate BookInuseMapper
IBookInuseService --> BookInuseController:返回上架信息
deactivate IBookInuseService
BookInuseController --> index.jsp:返回上架信息
deactivate BookInuseController
index.jsp --> 管理员:显示上架信息
deactivate index.jsp

@enduml